import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/page-hero";
import drinks from "@/assets/seasonal-drinks.jpg";

const seasonalDrinks = [
  { number: "01", name: "Клюквенный раф", note: "Клюква, ваниль и сливочная пена", price: "390 ₽" },
  { number: "02", name: "Пряный мокко", note: "Тёмный шоколад, корица и апельсин", price: "420 ₽" },
  { number: "03", name: "Хвойный латте", note: "Розмарин, мёд и мягкий эспрессо", price: "390 ₽" },
  { number: "04", name: "Грушевый чай", note: "Груша, чабрец и зимние специи", price: "350 ₽" },
];

export const Route=createFileRoute("/offers")({head:()=>({meta:[{title:"Акции — С теплом и Уютом"},{name:"description",content:"Сезонные акции и предложения кофейни."},{property:"og:title",content:"Акции — С теплом и Уютом"},{property:"og:description",content:"Сезонные акции и предложения кофейни."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Offers});
function Offers(){return <><PageHero eyebrow="Акции" title="Поводы согреться вместе" description="Небольшие приятности для зимних встреч, постоянных гостей и тех, кто заглянул впервые."/><section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-20 lg:grid-cols-2 lg:gap-12 lg:px-8"><div className="group overflow-hidden"><img src={drinks} alt="Зимние напитки со специями" width={1408} height={1008} className="aspect-[4/3] w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.035] sm:aspect-square"/></div><div className="grid min-w-0 gap-px bg-border">{[['−20%','на второй сезонный напиток после 18:00'],['6-й кофе','в подарок по карте постоянного гостя'],['Каждый вторник','печенье к большому капучино бесплатно']].map((x,index)=><article key={x[0]} className={`offer-row min-w-0 bg-background p-6 sm:p-7 animation-delay-${(index + 1) * 100}`}><p className="font-display text-3xl text-primary sm:text-4xl">{x[0]}</p><p className="mt-3 leading-7 text-muted-foreground">{x[1]}</p></article>)}</div></section><section className="bg-fir text-secondary-foreground"><div className="mx-auto max-w-7xl px-5 py-16 sm:py-20 lg:px-8 lg:py-24"><p className="text-xs font-semibold uppercase opacity-65">Зимняя коллекция</p><div className="mt-5 grid gap-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><h2 className="font-display text-4xl leading-tight sm:text-5xl">Четыре вкуса сезона</h2><p className="max-w-sm text-sm leading-6 opacity-70 sm:text-right">Готовим до конца зимы — горячими или тёплыми, на обычном или растительном молоке.</p></div><div className="mt-10 grid gap-px bg-secondary-foreground/20 sm:grid-cols-2 lg:mt-12 lg:grid-cols-4">{seasonalDrinks.map((drink,index)=><article key={drink.name} className={`drink-card group min-w-0 bg-fir p-6 sm:p-7 animation-delay-${(index + 1) * 100}`}><div className="flex items-start justify-between gap-4"><span className="text-xs opacity-45">{drink.number}</span><span className="text-sm font-semibold text-primary-foreground">{drink.price}</span></div><div className="mt-16 transition-transform duration-300 group-hover:-translate-y-2 sm:mt-20"><h3 className="font-display text-2xl leading-snug">{drink.name}</h3><p className="mt-3 text-sm leading-6 opacity-65">{drink.note}</p></div></article>)}</div></div></section></>}